SIMPLE_VAR = coucou
var2 = ${SIMPLE_VAR}3
toto = allo ${SPACES_BEFORE_TAB}
SPACES_BEFORE_TAB =  	  var_beginning	var_end

sparse_rule: depa depb

	command 1

	command 2

 B 	 =  	  B_var_beginning	B_var_end

packed_rule: depa depb
	command 1
	command 2

command_space_rule: depa depb
		echo spaces before
	echo spaces after    

simple_rule: simple_dep

no_dep_rule:

variable_rule: beginning ${SIMPLE_VAR} end
	echo "shouldn't be expanded: ${SIMPLE_VAR}"
